### ISSUE TITLE
Deixar o campo nome obrigatorio e a idade não pode ser negativa.

### ISSUE THREAD

**Issue by joathan** [raonircl/api-postgresql#2]
Hoje o projeto conta com dois atributos, nome e idade. 
a idéia é que o nome seja obrigatório e a idade não pode ser negativa, afinal de contas ninguém tem -3 anos. 
para essa tarefa, leia essa [doc](https://guides.rubyonrails.org/active_record_validations.html).

**Comment by raonircl** [comment]
Terminado!
